apiVersion: v1
kind: Service
metadata:
  name: animekaisen-metrics
  namespace: animekaisen
  labels:
    app: animekaisen
spec:
  selector:
    app: animekaisen
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
