apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: animekaisen
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - animekaisen
  selector:
    matchLabels:
      app: animekaisen
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
